name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# if there are multiple jobs, they will run in parallel
jobs:
  build:
    # choose OS
    runs-on: ubuntu-latest

    steps:
      # clone repo to new VM
      - uses: actions/checkout@v3
      # install node
      - name: Setup Node
        uses: actions/setup-node@v3
      # cache dependencies
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          # if hash of package lock hasn't changed, use the cache
          key: npm-${{ hashFiles('**/package-lock.json') }}
      # similar to npm install
      - run: npm ci
      # build
      - run: npm run build

  unit-test:
    # choose OS
    runs-on: ubuntu-latest

    steps:
      # clone repo to new VM
      - uses: actions/checkout@v3
      # install node
      - name: Setup Node
        uses: actions/setup-node@v3
      # cache dependencies
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          # if hash of package lock hasn't changed, use the cache
          key: npm-${{ hashFiles('**/package-lock.json') }}
      # similar to npm install
      - run: npm ci
      # run tests
      - run: npm test
